version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      pydantic-group:
        patterns:
          - "pydantic"
          - "pydantic-core"
          - "pydantic-settings"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "python"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"