"""Turkiye'nin 81 ili (plaka kodu + ad). MGMWeather'dan bagimsiz."""

import copy
from typing import Any

# GET /iller doğrudan buradan döner
TURKIYE_ILLERI: list[dict[str, Any]] = [
    {"plakaKodu": 1, "il": "Adana"},
    {"plakaKodu": 2, "il": "Adıyaman"},
    {"plakaKodu": 3, "il": "Afyonkarahisar"},
    {"plakaKodu": 4, "il": "Ağrı"},
    {"plakaKodu": 5, "il": "Amasya"},
    {"plakaKodu": 6, "il": "Ankara"},
    {"plakaKodu": 7, "il": "Antalya"},
    {"plakaKodu": 8, "il": "Artvin"},
    {"plakaKodu": 9, "il": "Aydın"},
    {"plakaKodu": 10, "il": "Balıkesir"},
    {"plakaKodu": 11, "il": "Bilecik"},
    {"plakaKodu": 12, "il": "Bingöl"},
    {"plakaKodu": 13, "il": "Bitlis"},
    {"plakaKodu": 14, "il": "Bolu"},
    {"plakaKodu": 15, "il": "Burdur"},
    {"plakaKodu": 16, "il": "Bursa"},
    {"plakaKodu": 17, "il": "Çanakkale"},
    {"plakaKodu": 18, "il": "Çankırı"},
    {"plakaKodu": 19, "il": "Çorum"},
    {"plakaKodu": 20, "il": "Denizli"},
    {"plakaKodu": 21, "il": "Diyarbakır"},
    {"plakaKodu": 22, "il": "Edirne"},
    {"plakaKodu": 23, "il": "Elazığ"},
    {"plakaKodu": 24, "il": "Erzincan"},
    {"plakaKodu": 25, "il": "Erzurum"},
    {"plakaKodu": 26, "il": "Eskişehir"},
    {"plakaKodu": 27, "il": "Gaziantep"},
    {"plakaKodu": 28, "il": "Giresun"},
    {"plakaKodu": 29, "il": "Gümüşhane"},
    {"plakaKodu": 30, "il": "Hakkâri"},
    {"plakaKodu": 31, "il": "Hatay"},
    {"plakaKodu": 32, "il": "Isparta"},
    {"plakaKodu": 33, "il": "Mersin"},
    {"plakaKodu": 34, "il": "İstanbul"},
    {"plakaKodu": 35, "il": "İzmir"},
    {"plakaKodu": 36, "il": "Kars"},
    {"plakaKodu": 37, "il": "Kastamonu"},
    {"plakaKodu": 38, "il": "Kayseri"},
    {"plakaKodu": 39, "il": "Kırklareli"},
    {"plakaKodu": 40, "il": "Kırşehir"},
    {"plakaKodu": 41, "il": "Kocaeli"},
    {"plakaKodu": 42, "il": "Konya"},
    {"plakaKodu": 43, "il": "Kütahya"},
    {"plakaKodu": 44, "il": "Malatya"},
    {"plakaKodu": 45, "il": "Manisa"},
    {"plakaKodu": 46, "il": "Kahramanmaraş"},
    {"plakaKodu": 47, "il": "Mardin"},
    {"plakaKodu": 48, "il": "Muğla"},
    {"plakaKodu": 49, "il": "Muş"},
    {"plakaKodu": 50, "il": "Nevşehir"},
    {"plakaKodu": 51, "il": "Niğde"},
    {"plakaKodu": 52, "il": "Ordu"},
    {"plakaKodu": 53, "il": "Rize"},
    {"plakaKodu": 54, "il": "Sakarya"},
    {"plakaKodu": 55, "il": "Samsun"},
    {"plakaKodu": 56, "il": "Siirt"},
    {"plakaKodu": 57, "il": "Sinop"},
    {"plakaKodu": 58, "il": "Sivas"},
    {"plakaKodu": 59, "il": "Tekirdağ"},
    {"plakaKodu": 60, "il": "Tokat"},
    {"plakaKodu": 61, "il": "Trabzon"},
    {"plakaKodu": 62, "il": "Tunceli"},
    {"plakaKodu": 63, "il": "Şanlıurfa"},
    {"plakaKodu": 64, "il": "Uşak"},
    {"plakaKodu": 65, "il": "Van"},
    {"plakaKodu": 66, "il": "Yozgat"},
    {"plakaKodu": 67, "il": "Zonguldak"},
    {"plakaKodu": 68, "il": "Aksaray"},
    {"plakaKodu": 69, "il": "Bayburt"},
    {"plakaKodu": 70, "il": "Karaman"},
    {"plakaKodu": 71, "il": "Kırıkkale"},
    {"plakaKodu": 72, "il": "Batman"},
    {"plakaKodu": 73, "il": "Şırnak"},
    {"plakaKodu": 74, "il": "Bartın"},
    {"plakaKodu": 75, "il": "Ardahan"},
    {"plakaKodu": 76, "il": "Iğdır"},
    {"plakaKodu": 77, "il": "Yalova"},
    {"plakaKodu": 78, "il": "Karabük"},
    {"plakaKodu": 79, "il": "Kilis"},
    {"plakaKodu": 80, "il": "Osmaniye"},
    {"plakaKodu": 81, "il": "Düzce"},
]


def turkiye_illeri() -> list[dict[str, Any]]:
    return copy.deepcopy(TURKIYE_ILLERI)